import type { CSSProperties } from "react";

export const s = {
  layout: { display: "flex", height: "100%", minHeight: 0 } satisfies CSSProperties,
  side: {
    width: 236,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  sideHead: { padding: "16px 14px 10px", display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  toolbar: { display: "flex", alignItems: "center", gap: 2 } satisfies CSSProperties,
  eyebrow: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  tree: { flex: 1, overflowY: "auto", padding: "4px 8px" } satisfies CSSProperties,
  footer: {
    padding: "10px 14px",
    borderTop: "1px solid var(--border)",
    fontSize: 11.5,
    color: "var(--text-muted)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" } satisfies CSSProperties,
  mainHead: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "14px 24px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  path: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  tabs: {
    display: "flex",
    gap: 2,
    padding: 2,
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  tab: {
    padding: "3px 10px",
    borderRadius: 5,
    border: "none",
    background: "transparent",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  tabActive: { background: "var(--bg-elevated)", color: "var(--text-primary)", fontWeight: 600 } satisfies CSSProperties,
  tabDisabled: { opacity: 0.6, cursor: "not-allowed" } satisfies CSSProperties,
  usedBy: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  preview: { padding: "20px 28px", overflowY: "auto", fontSize: 14 } satisfies CSSProperties,
  center: { padding: 32 } satisfies CSSProperties,
};
