import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillDrawer. */
export const s = {
  footer: { display: "flex", justifyContent: "flex-end", gap: 10 } satisfies CSSProperties,
  dropzone: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    padding: "28px 16px",
    borderRadius: 10,
    border: "1px dashed var(--border-strong)",
    background: "var(--bg-surface)",
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  dropzoneLabel: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  filename: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  error: {
    marginTop: 14,
    fontSize: 12.5,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    border: "1px solid var(--crit)",
    borderRadius: 7,
    padding: "8px 10px",
  } satisfies CSSProperties,
  preview: { marginTop: 18 } satisfies CSSProperties,
  trust: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    border: "1px solid var(--warn)",
    borderRadius: 7,
    padding: "10px 12px",
    marginBottom: 16,
  } satisfies CSSProperties,
  trustTitle: { fontWeight: 650 } satisfies CSSProperties,
  previewTitle: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  row: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  name: { fontSize: 15, fontWeight: 650 } satisfies CSSProperties,
  description: {
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    margin: "8px 0 4px",
  } satisfies CSSProperties,
  sourceFile: { fontSize: 11.5, color: "var(--text-muted)", marginBottom: 12 } satisfies CSSProperties,
  body: {
    fontSize: 13,
    lineHeight: 1.55,
    maxHeight: 320,
    overflowY: "auto",
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  skipped: { marginTop: 16 } satisfies CSSProperties,
  skippedTitle: { fontSize: 12.5, fontWeight: 650, marginBottom: 8 } satisfies CSSProperties,
  skippedList: { listStyle: "none", display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  skippedItem: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 10,
    fontSize: 12,
  } satisfies CSSProperties,
  skippedPath: { color: "var(--text-secondary)" } satisfies CSSProperties,
  skippedMeta: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  skippedHint: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    lineHeight: 1.5,
    marginTop: 8,
  } satisfies CSSProperties,
} as const;
