import type { CSSProperties } from "react";

/* Shared style tokens for PrBriefCard and its subcomponents (RiskRow, FocusRow),
   imported as `../../styles` from _components/*. CSS-var tokens from src/vendor/ui/styles.css. */
export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  summary: {
    fontSize: 14,
    color: "var(--text-primary)",
    lineHeight: 1.55,
  } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  staleBadge: {
    color: "var(--warn)",
    background: "var(--warn-bg)",
    borderRadius: 5,
    padding: "2px 8px",
    fontWeight: 600,
  } satisfies CSSProperties,
  note: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  error: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    fontSize: 13,
    color: "var(--crit)",
  } satisfies CSSProperties,
  subhead: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  hint: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  row: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  rowHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  rowButton: {
    background: "transparent",
    border: "none",
    padding: 0,
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 500,
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  focusButton: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    flexWrap: "wrap",
    width: "100%",
    background: "transparent",
    border: "none",
    padding: 0,
    textAlign: "left",
    cursor: "pointer",
    color: "var(--text-secondary)",
    fontSize: 13,
  } satisfies CSSProperties,
  toggle: {
    background: "transparent",
    border: "none",
    padding: 0,
    color: "var(--accent-text)",
    fontSize: 12,
    cursor: "pointer",
  } satisfies CSSProperties,
  severity: {
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  path: {
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  explanation: {
    margin: 0,
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  notInDiff: {
    fontSize: 12,
    color: "var(--warn)",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  skeletons: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
} as const;
